@startuml tests.modules.ecoindex.ecoindex-sequence
skinparam BoxPadding 10
skinparam ParticipantPadding 5
skinparam NoteBackgroundColor Cornsilk
skinparam NoteBorderColor Sienna
hide footbox

[o-> "tests.modules.ecoindex\necoindex"
note right: line 73

"tests.modules.ecoindex\necoindex" -> "tests.modules.ecoindex\nto_quantile_position" ++
note left: line 74
note right: line 51

"tests.modules.ecoindex\nto_quantile_position" -> "tests.modules.ecoindex\nacknowledge_interpolation" ++
note left: line 64
note right: line 68

return 
note right: line 70
|||

return 14.086614173228346
note right: line 65
|||

"tests.modules.ecoindex\necoindex" -> "tests.modules.ecoindex\nto_quantile_position" ++
note left: line 75
note right: line 51

"tests.modules.ecoindex\nto_quantile_position" -> "tests.modules.ecoindex\nacknowledge_interpolation" ++
note left: line 64
note right: line 68

return 
note right: line 70
|||

return 9.0
note right: line 65
|||

"tests.modules.ecoindex\necoindex" -> "tests.modules.ecoindex\nto_quantile_position" ++
note left: line 76
note right: line 51

"tests.modules.ecoindex\nto_quantile_position" -> "tests.modules.ecoindex\nacknowledge_interpolation" ++
note left: line 64
note right: line 68

return 
note right: line 70
|||

return 10.258464616154038
note right: line 65
|||

"tests.modules.ecoindex\necoindex" -> "tests.modules.ecoindex\nvalidate_ecoindex" ++
note left: line 78
note right: line 81

return 41.23474405346743
note right: line 83
|||

[<-- "tests.modules.ecoindex\necoindex": 41.23474405346743
note right: line 78

footer Generated by //pydoctrace//
@enduml
