@startuml tests.integrations.calldepth.depth_1-component
skinparam BoxPadding 10
skinparam componentStyle rectangle

package tests.integrations {
  frame calldepth {
    [tests.integrations.calldepth.depth_1] as "depth_1" << @trace_to_component_puml >>
    [tests.integrations.calldepth.depth_2] as "depth_2"
    [tests.integrations.calldepth.depth_3] as "depth_3"
    [tests.integrations.calldepth.depth_4] as "depth_4"
    [tests.integrations.calldepth.depth_5] as "depth_5"
    [tests.integrations.calldepth.depth_6] as "depth_6"
  }
}
[tests.integrations.calldepth.depth_1] --> [tests.integrations.calldepth.depth_2] : 1
[tests.integrations.calldepth.depth_1] <.. [tests.integrations.calldepth.depth_2] : 10
[tests.integrations.calldepth.depth_2] --> [tests.integrations.calldepth.depth_3] : 2
[tests.integrations.calldepth.depth_2] <.. [tests.integrations.calldepth.depth_3] : 9
[tests.integrations.calldepth.depth_3] --> [tests.integrations.calldepth.depth_4] : 3
[tests.integrations.calldepth.depth_3] <.. [tests.integrations.calldepth.depth_4] : 8
[tests.integrations.calldepth.depth_4] --> [tests.integrations.calldepth.depth_5] : 4, 12
[tests.integrations.calldepth.depth_4] <.. [tests.integrations.calldepth.depth_5] : 7, 15
[tests.integrations.calldepth.depth_5] --> [tests.integrations.calldepth.depth_6] : 5, 13
[tests.integrations.calldepth.depth_5] <.. [tests.integrations.calldepth.depth_6] : 6, 14
[tests.integrations.calldepth.depth_1] --> [tests.integrations.calldepth.depth_4] : 11
[tests.integrations.calldepth.depth_1] <.. [tests.integrations.calldepth.depth_4] : 16

footer Generated by //pydoctrace//
@enduml
