@startuml tests.modules.classes.complexclasses.main_process_with_factory-component
skinparam BoxPadding 10
skinparam componentStyle rectangle
set separator .
!pragma useIntermediatePackages false

package tests.modules.classes {
  frame complexclasses {
    [main_process_with_factory] << @trace_to_component_puml >>
    frame ProcessMock {
      [~__init~__]
      [start]
      [join]
    }
    frame DiffCollector {
      [_diff]
    }
  }
  package collector {
    frame Collector {
      [collector_factory]
      [~__init~__]
      [collect]
      [_aggregate]
    }
  }
}
[tests.modules.classes.complexclasses.main_process_with_factory] -> [tests.modules.classes.complexclasses.ProcessMock.~__init~__] : 1
[tests.modules.classes.complexclasses.main_process_with_factory] <. [tests.modules.classes.complexclasses.ProcessMock.~__init~__] : 2
[tests.modules.classes.complexclasses.main_process_with_factory] -> [tests.modules.classes.complexclasses.ProcessMock.start] : 3
[tests.modules.classes.complexclasses.main_process_with_factory] <. [tests.modules.classes.complexclasses.ProcessMock.start] : 4
[tests.modules.classes.complexclasses.main_process_with_factory] -> [tests.modules.classes.complexclasses.ProcessMock.join] : 5
[tests.modules.classes.complexclasses.main_process_with_factory] <. [tests.modules.classes.complexclasses.ProcessMock.join] : 16
[tests.modules.classes.complexclasses.ProcessMock.join] -> [tests.modules.classes.collector.Collector.collector_factory] : 6
[tests.modules.classes.complexclasses.ProcessMock.join] <. [tests.modules.classes.collector.Collector.collector_factory] : 15
[tests.modules.classes.collector.Collector.collector_factory] --> [tests.modules.classes.collector.Collector.~__init~__] : 7
[tests.modules.classes.collector.Collector.collector_factory] <.. [tests.modules.classes.collector.Collector.~__init~__] : 8
[tests.modules.classes.collector.Collector.collector_factory] --> [tests.modules.classes.collector.Collector.collect] : 9
[tests.modules.classes.collector.Collector.collector_factory] <.. [tests.modules.classes.collector.Collector.collect] : 14
[tests.modules.classes.collector.Collector.collect] --> [tests.modules.classes.collector.Collector._aggregate] : 10
[tests.modules.classes.collector.Collector.collect] <.. [tests.modules.classes.collector.Collector._aggregate] : 11
[tests.modules.classes.collector.Collector.collect] -> [tests.modules.classes.complexclasses.DiffCollector._diff] : 12
[tests.modules.classes.collector.Collector.collect] <. [tests.modules.classes.complexclasses.DiffCollector._diff] : 13

footer Generated by //pydoctrace//
@enduml
