@startuml tests.modules.classes.complexclasses.main_start_game-component
skinparam BoxPadding 10
skinparam componentStyle rectangle

package tests.modules.classes {
  frame complexclasses {
    [tests.modules.classes.complexclasses.main_start_game] as "main_start_game" << @trace_to_component_puml >>
    frame TicTacToe {
      [tests.modules.classes.complexclasses.TicTacToe.start_game] as "start_game"
      [tests.modules.classes.complexclasses.TicTacToe.~__init~__] as "~__init~__"
      [tests.modules.classes.complexclasses.TicTacToe.place_piece] as "place_piece"
      frame SquareBoard {
        [tests.modules.classes.complexclasses.TicTacToe.SquareBoard.~__init~__] as "~__init~__"
      }
    }
    frame Game {
      [tests.modules.classes.complexclasses.Game.~__init~__] as "~__init~__"
      frame Player {
        [tests.modules.classes.complexclasses.Game.Player.~__init~__] as "~__init~__"
      }
      frame Board {
        [tests.modules.classes.complexclasses.Game.Board.~__init~__] as "~__init~__"
        frame Piece {
          [tests.modules.classes.complexclasses.Game.Board.Piece.~__init~__] as "~__init~__"
        }
      }
    }
  }
}
[tests.modules.classes.complexclasses.main_start_game] -> [tests.modules.classes.complexclasses.TicTacToe.start_game] : 1
[tests.modules.classes.complexclasses.main_start_game] <. [tests.modules.classes.complexclasses.TicTacToe.start_game] : 14
[tests.modules.classes.complexclasses.TicTacToe.start_game] -> [tests.modules.classes.complexclasses.Game.Player.~__init~__] : 2, 4
[tests.modules.classes.complexclasses.TicTacToe.start_game] <. [tests.modules.classes.complexclasses.Game.Player.~__init~__] : 3, 5
[tests.modules.classes.complexclasses.TicTacToe.start_game] --> [tests.modules.classes.complexclasses.TicTacToe.~__init~__] : 6
[tests.modules.classes.complexclasses.TicTacToe.start_game] <.. [tests.modules.classes.complexclasses.TicTacToe.~__init~__] : 13
[tests.modules.classes.complexclasses.TicTacToe.~__init~__] -> [tests.modules.classes.complexclasses.TicTacToe.SquareBoard.~__init~__] : 7
[tests.modules.classes.complexclasses.TicTacToe.~__init~__] <. [tests.modules.classes.complexclasses.TicTacToe.SquareBoard.~__init~__] : 10
[tests.modules.classes.complexclasses.TicTacToe.SquareBoard.~__init~__] -> [tests.modules.classes.complexclasses.Game.Board.~__init~__] : 8
[tests.modules.classes.complexclasses.TicTacToe.SquareBoard.~__init~__] <. [tests.modules.classes.complexclasses.Game.Board.~__init~__] : 9
[tests.modules.classes.complexclasses.TicTacToe.~__init~__] -> [tests.modules.classes.complexclasses.Game.~__init~__] : 11
[tests.modules.classes.complexclasses.TicTacToe.~__init~__] <. [tests.modules.classes.complexclasses.Game.~__init~__] : 12
[tests.modules.classes.complexclasses.main_start_game] -> [tests.modules.classes.complexclasses.TicTacToe.place_piece] : 15, 19
[tests.modules.classes.complexclasses.main_start_game] <. [tests.modules.classes.complexclasses.TicTacToe.place_piece] : 18, 22
[tests.modules.classes.complexclasses.TicTacToe.place_piece] -> [tests.modules.classes.complexclasses.Game.Board.Piece.~__init~__] : 16, 20
[tests.modules.classes.complexclasses.TicTacToe.place_piece] <. [tests.modules.classes.complexclasses.Game.Board.Piece.~__init~__] : 17, 21

footer Generated by //pydoctrace//
@enduml
