@startuml tests.modules.classes.namedtuples.main_namedtuple-component
skinparam BoxPadding 10
skinparam componentStyle rectangle
set separator .
!pragma useIntermediatePackages false

package tests.modules.classes {
  frame namedtuples {
    [main_namedtuple] << @trace_to_component_puml >>
    [create_person]
    frame Person {
      [~__new~__]
      [full_name]
    }
  }
}
package urllib {
  frame parse {
    [urlsplit]
    [_coerce_args]
    [_remove_unsafe_bytes_from_url]
    [_splitnetloc]
    [_checknetloc]
    [_noop]
    frame SplitResult {
      [~__new~__]
    }
  }
}
[tests.modules.classes.namedtuples.main_namedtuple] -> [urllib.parse.urlsplit] : 1
[tests.modules.classes.namedtuples.main_namedtuple] <. [urllib.parse.urlsplit] : 16
[urllib.parse.urlsplit] --> [urllib.parse._coerce_args] : 2
[urllib.parse.urlsplit] <.. [urllib.parse._coerce_args] : 3
[urllib.parse.urlsplit] --> [urllib.parse._remove_unsafe_bytes_from_url] : 4, 6
[urllib.parse.urlsplit] <.. [urllib.parse._remove_unsafe_bytes_from_url] : 5, 7
[urllib.parse.urlsplit] --> [urllib.parse._splitnetloc] : 8
[urllib.parse.urlsplit] <.. [urllib.parse._splitnetloc] : 9
[urllib.parse.urlsplit] --> [urllib.parse._checknetloc] : 10
[urllib.parse.urlsplit] <.. [urllib.parse._checknetloc] : 11
[urllib.parse.urlsplit] -> [urllib.parse.SplitResult.~__new~__] : 12
[urllib.parse.urlsplit] <. [urllib.parse.SplitResult.~__new~__] : 13
[urllib.parse.urlsplit] --> [urllib.parse._noop] : 14
[urllib.parse.urlsplit] <.. [urllib.parse._noop] : 15
[tests.modules.classes.namedtuples.main_namedtuple] --> [tests.modules.classes.namedtuples.create_person] : 17
[tests.modules.classes.namedtuples.main_namedtuple] <.. [tests.modules.classes.namedtuples.create_person] : 20
[tests.modules.classes.namedtuples.create_person] -> [tests.modules.classes.namedtuples.Person.~__new~__] : 18
[tests.modules.classes.namedtuples.create_person] <. [tests.modules.classes.namedtuples.Person.~__new~__] : 19
[tests.modules.classes.namedtuples.main_namedtuple] -> [tests.modules.classes.namedtuples.Person.full_name] : 21
[tests.modules.classes.namedtuples.main_namedtuple] <. [tests.modules.classes.namedtuples.Person.full_name] : 22

footer Generated by //pydoctrace//
@enduml
