@startuml tests.modules.classes.namedtuples.main_namedtuple_disambiguation-component
skinparam BoxPadding 10
skinparam componentStyle rectangle
set separator .
!pragma useIntermediatePackages false

package tests.modules.classes {
  frame namedtuples {
    [main_namedtuple_disambiguation] << @trace_to_component_puml >>
    [update_namedtuple]
    frame Person {
      [~__new~__]
    }
    frame Pet {
      [~__new~__]
    }
  }
}
package collections {
  frame namedtuple {
    [_replace]
    [_make]
    [~__getnewargs~__]
    [_asdict]
    [~__repr~__]
  }
}
frame copyreg {
  [_slotnames]
}
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] -> [tests.modules.classes.namedtuples.Person.~__new~__] : 1
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] <. [tests.modules.classes.namedtuples.Person.~__new~__] : 2
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] --> [tests.modules.classes.namedtuples.update_namedtuple] : 3, 11
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] <.. [tests.modules.classes.namedtuples.update_namedtuple] : 8, 16
[tests.modules.classes.namedtuples.update_namedtuple] -> [collections.namedtuple._replace] : 4, 12
[tests.modules.classes.namedtuples.update_namedtuple] <. [collections.namedtuple._replace] : 7, 15
[collections.namedtuple._replace] --> [collections.namedtuple._make] : 5, 13
[collections.namedtuple._replace] <.. [collections.namedtuple._make] : 6, 14
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] -> [tests.modules.classes.namedtuples.Pet.~__new~__] : 9
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] <. [tests.modules.classes.namedtuples.Pet.~__new~__] : 10
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] -> [collections.namedtuple.~__getnewargs~__] : 17
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] <. [collections.namedtuple.~__getnewargs~__] : 18
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] -> [copyreg._slotnames] : 19
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] <. [copyreg._slotnames] : 20
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] -> [collections.namedtuple._asdict] : 21
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] <. [collections.namedtuple._asdict] : 22
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] -> [collections.namedtuple.~__repr~__] : 23
[tests.modules.classes.namedtuples.main_namedtuple_disambiguation] <. [collections.namedtuple.~__repr~__] : 24

footer Generated by //pydoctrace//
@enduml
