@startuml tests.modules.classes.dataclass.main_dataclass-component
skinparam BoxPadding 10
skinparam componentStyle rectangle

rectangle None #line:transparent;text:transparent {
  package tests.modules.classes {
    frame dataclass {
      [tests.modules.classes.dataclass.main_dataclass] as "main_dataclass" << @trace_to_component_puml >>
      [tests.modules.classes.dataclass.create_person] as "create_person"
      frame Person {
        [tests.modules.classes.dataclass.Person.~__init~__] as "~__init~__"
        [tests.modules.classes.dataclass.Person.~__hash~__] as "~__hash~__"
        [tests.modules.classes.dataclass.Person.~__repr~__] as "~__repr~__"
        [tests.modules.classes.dataclass.Person.~__eq~__] as "~__eq~__"
        [tests.modules.classes.dataclass.Person.full_name] as "full_name"
      }
    }
  }
  frame builtins {
    [builtins.~__repr~__] as "~__repr~__"
  }
  frame codecs {
    [codecs.reset] as "reset"
    frame IncrementalDecoder {
      [codecs.IncrementalDecoder.reset] as "reset"
    }
  }
}
[tests.modules.classes.dataclass.main_dataclass] --> [tests.modules.classes.dataclass.create_person] : 1
[tests.modules.classes.dataclass.main_dataclass] <.. [tests.modules.classes.dataclass.create_person] : 4
[tests.modules.classes.dataclass.create_person] -> [tests.modules.classes.dataclass.Person.~__init~__] : 2
[tests.modules.classes.dataclass.create_person] <. [tests.modules.classes.dataclass.Person.~__init~__] : 3
[tests.modules.classes.dataclass.main_dataclass] -> [tests.modules.classes.dataclass.Person.~__hash~__] : 5
[tests.modules.classes.dataclass.main_dataclass] <. [tests.modules.classes.dataclass.Person.~__hash~__] : 6
[tests.modules.classes.dataclass.main_dataclass] -> [tests.modules.classes.dataclass.Person.~__init~__] : 7
[tests.modules.classes.dataclass.main_dataclass] <. [tests.modules.classes.dataclass.Person.~__init~__] : 8
[tests.modules.classes.dataclass.main_dataclass] -> [tests.modules.classes.dataclass.Person.~__repr~__] : 9, 15
[tests.modules.classes.dataclass.main_dataclass] <. [tests.modules.classes.dataclass.Person.~__repr~__] : 12, 18
[tests.modules.classes.dataclass.Person.~__repr~__] -> [builtins.~__repr~__] : 10, 16
[tests.modules.classes.dataclass.Person.~__repr~__] <. [builtins.~__repr~__] : 11, 17
[tests.modules.classes.dataclass.main_dataclass] -> [tests.modules.classes.dataclass.Person.~__eq~__] : 13
[tests.modules.classes.dataclass.main_dataclass] <. [tests.modules.classes.dataclass.Person.~__eq~__] : 14
[tests.modules.classes.dataclass.main_dataclass] -> [codecs.reset] : 19, 23
[tests.modules.classes.dataclass.main_dataclass] <. [codecs.reset] : 22, 26
[codecs.reset] -> [codecs.IncrementalDecoder.reset] : 20, 24
[codecs.reset] <. [codecs.IncrementalDecoder.reset] : 21, 25
[tests.modules.classes.dataclass.main_dataclass] -> [tests.modules.classes.dataclass.Person.full_name] : 27
[tests.modules.classes.dataclass.main_dataclass] <. [tests.modules.classes.dataclass.Person.full_name] : 28

footer Generated by //pydoctrace//
@enduml
