@startuml tests.modules.classes.basicclass.main_basic_class-component
skinparam BoxPadding 10
skinparam componentStyle rectangle

package tests.modules.classes {
  frame basicclass {
    [tests.modules.classes.basicclass.main_basic_class] as "main_basic_class" << @trace_to_component_puml >>
    [tests.modules.classes.basicclass.create_person] as "create_person"
    frame Person {
      [tests.modules.classes.basicclass.Person.factory] as "factory"
      [tests.modules.classes.basicclass.Person.~__init~__] as "~__init~__"
      [tests.modules.classes.basicclass.Person.full_name] as "full_name"
    }
  }
}
[tests.modules.classes.basicclass.main_basic_class] --> [tests.modules.classes.basicclass.create_person] : 1
[tests.modules.classes.basicclass.main_basic_class] <.. [tests.modules.classes.basicclass.create_person] : 6
[tests.modules.classes.basicclass.create_person] -> [tests.modules.classes.basicclass.Person.factory] : 2
[tests.modules.classes.basicclass.create_person] <. [tests.modules.classes.basicclass.Person.factory] : 5
[tests.modules.classes.basicclass.Person.factory] --> [tests.modules.classes.basicclass.Person.~__init~__] : 3
[tests.modules.classes.basicclass.Person.factory] <.. [tests.modules.classes.basicclass.Person.~__init~__] : 4
[tests.modules.classes.basicclass.main_basic_class] -> [tests.modules.classes.basicclass.Person.full_name] : 7
[tests.modules.classes.basicclass.main_basic_class] <. [tests.modules.classes.basicclass.Person.full_name] : 8

footer Generated by //pydoctrace//
@enduml
