@startuml tests.modules.factorial.factorial_with_checker-sequence
skinparam BoxPadding 10
skinparam ParticipantPadding 5
skinparam NoteBackgroundColor Cornsilk
skinparam NoteBorderColor Sienna
hide footbox

[o-> "tests.modules.factorial\nfactorial_with_checker"
note right: line 48

"tests.modules.factorial\nfactorial_with_checker" -> "tests.modules.factorial.validator\ncheck_or_wrap_error" ++
note left: line 50
note right: line 23

"tests.modules.factorial.validator\ncheck_or_wrap_error" -> "tests.modules.factorial.validator\nis_positive_int" ++
note left: line 25
note right: line 4

"tests.modules.factorial.validator\nis_positive_int" -> "tests.modules.factorial.validator\nraise_value_error" ++
note left: line 7
note right: line 10

"tests.modules.factorial.validator\nis_positive_int" o<--x "tests.modules.factorial.validator\nraise_value_error": ""ValueError""\nValue must be a positive integer, got int_is_resting.
deactivate "tests.modules.factorial.validator\nraise_value_error"
note right: line 11
note left: line 7

"tests.modules.factorial.validator\ncheck_or_wrap_error" o<--x "tests.modules.factorial.validator\nis_positive_int": ""ValueError""\nValue must be a positive integer, got int_is_resting.
deactivate "tests.modules.factorial.validator\nis_positive_int"
note right: line 7
note left: line 25

"tests.modules.factorial\nfactorial_with_checker" o<--x "tests.modules.factorial.validator\ncheck_or_wrap_error": ""FactorialError""\nFactorialError()
deactivate "tests.modules.factorial.validator\ncheck_or_wrap_error"
note right: line 28
note left: line 50

"tests.modules.factorial\nfactorial_with_checker" -> "tests.modules.factorial.validator\nlog_factorial_error" ++
note left: line 52
note right: line 18

return 
note right: line 20
|||

[<-- "tests.modules.factorial\nfactorial_with_checker": 
note right: line 54

footer Generated by //pydoctrace//
@enduml
